 # .readthedocs.yml
# Read the Docs configuration file
version: 2

# Python config
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-latest
  jobs:
    pre_build:
      - pytest


conda:
  environment: ./docs/environment.yml

sphinx:
  configuration: ./docs/conf.py
  builder: html
