# .readthedocs.yml
# Read the Docs configuration file
version: 2


# Python config
build:
  os: ubuntu-22.04
  image: latest
  tools:
    python:
      version: 3.12
      system_packages: true
    conda:
      environment: docs/environment.yml

# Sphinx config
sphinx:
  builder: html
  configuration: docs/conf.py

