name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-ultraplot:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v2.0.3
        with:
          environment-file: ./environment-dev.yml
          init-shell: bash
          create-args: --verbose
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-downloads: false

      - name: Test Ultraplot
        shell: bash -el {0}
        run: |
          micromamba activate ultraplot-dev
          pip install .
          python -m pytest
