name: Linter check
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v2.0.3
        with:
          environment-file: ./environment-dev.yml
          init-shell: bash
          create-args: --verbose
          cache-environment: true
          cache-downloads: false

      - name: "Apply linter"
        shell: bash -el {0}
        run: |
          micromamba activate ultraplot-dev
          pip install .
          pip install black
          black --check --diff ultraplot
